<a href="https://colab.research.google.com/github/laxmiharikumar/Tips-Tricks/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental concepts of tensors using tensorflow
- Introduction to Tensors

# Introduction to Tensors

In [43]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [44]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [45]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [46]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [47]:
# Check the number of dimensions of vector
vector.ndim

1

In [48]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [49]:
#Check the number of dimensions of matrix
matrix.ndim

2

In [50]:
# Create  another matrix
another_matrix = tf.constant([[10., 7.],
                              [2., 3.],
                              [8., 9.]], dtype=tf.float16) # specify the datatype with the dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 2.,  3.],
       [ 8.,  9.]], dtype=float16)>

In [51]:
another_matrix.ndim

2

In [52]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3], [4,5,6]],
                      [[7,8,9], [10,11,12]],
                      [[13,14,15], [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [53]:
tensor.ndim

3

*   Scalar - a single number
*   Vector - a number with direction
*   Matrix - a 2 dimensional array of numbers
*   Tensor - an n dimenaional array of numbers where n >= 0


### Create tensor with `tf.Variable`

In [54]:
# Create the same tensor with tf.Variable
changeable_tensor = tf.Variable([10, 10])
unchangeable_tensor = tf.constant([10, 10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [55]:
# Change one of the variables in changeable tensor - THIS IS NOT THE WAY - hence commented
# changeable_tensor[0] = 5
# changeable_tensor

In [56]:
# Try .assign()
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 5, 10], dtype=int32)>

In [57]:
# Try to change unchangeable tensor - WE CANNOT CHANGE THIS TENSOR - HENCE COMMENTED
# unchangeable_tensor[0].assign(4)
# unchangeable_tensor

### Create random tensors

Random tensors are tensors of some arbitrary size that contain some random numbers

In [58]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [59]:
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [60]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [61]:
# Shuffle a tensor (valuable when you want to shuffle your data so that learning is not impacted)
not_shuffled = tf.constant([[10,7], [3,4], [2, 5]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [62]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [63]:
# To keep the same order use the global seed and operation level seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to create tensor

In [64]:
# Create a tensor of all ones
tf.ones([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [65]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between Numpy arrays and tensorflow  tensors is that tensors can be run on GPUs (much faster for numerical computing)

In [66]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [67]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [68]:
tensor_B = tf.constant(numpy_A, shape=(2,3,4))
tensor_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Get information from tensors


*   Shape
*   Rank
*   Axis or dimension
*   Size


In [69]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [70]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [71]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [72]:
# Get various attributes of our tensor
print("Data type of each element: ", rank_4_tensor.dtype)
print("Dimension of the tensor (rank): ", rank_4_tensor.ndim)
print("Shape of the tensor: ", rank_4_tensor.shape)
print("Elements along 0 axis: ", rank_4_tensor.shape[0])
print("Elements along nth axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in the tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in the tensor: ", tf.size(rank_4_tensor).numpy())

Data type of each element:  <dtype: 'float32'>
Dimension of the tensor (rank):  4
Shape of the tensor:  (2, 3, 4, 5)
Elements along 0 axis:  2
Elements along nth axis:  5
Total number of elements in the tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in the tensor:  120


### Indexing tensors

Tensors can be indexed like python lists

In [73]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [74]:
# get first 2 elements of every dimension
rank_4_tensor[:2]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [75]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [76]:
# Get first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [77]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7], [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [78]:
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [79]:
# Get the last item from each dimension of rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [80]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # ... means every axis before new addition
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [81]:
# Another way of doing the same
tf.expand_dims(rank_2_tensor, axis = -1) # -1 indicates expand the final dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [82]:
# Expand the 0 axis
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors

**Basic Operations**

+, -, *, /


In [83]:
# You can add values to a tensor with + operator
tensor_1 = tf.constant([[10,7], [3,4]])
tensor_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [84]:
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [85]:
tensor_1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [86]:
tensor_1 / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [87]:
# We can use built in operators as well
tf.multiply(tensor_1, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]], dtype=int32)>

**Matrix Multiplication**

Rules
*   The inner dimensions must match
*   Resulting matrix has the shape of outer dimensions



In [88]:
# Matrix multiplication in Tensorflow
tf.matmul(tensor_1, tensor_1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [89]:
# Matrix multiplication with python operator @
tensor_1 @ tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [90]:
# Create a tensor - (3,2) tensor
tensor_2 = tf.constant([[1,2],
                        [3,4],
                        [5,6]])
tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [91]:
# Create another (3, 2) tensor
tensor_3 = tf.constant([[7,8],
                        [9,10],
                        [11,12]])
tensor_3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

**Resource** - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [92]:
#Let's change the shape of tensor_3
tf.reshape(tensor_3,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [93]:
# Multiply these 2 tensors with reshape
# tensor_2 * resshaped tensor_3
tensor_2 @ tf.reshape(tensor_3,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [94]:
tf.matmul(tensor_2, tf.reshape(tensor_3,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [95]:
tf.matmul(tf.reshape(tensor_2,shape=(2,3)), tensor_3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [96]:
# Matrix multiplication with transpose
tf.matmul(tf.transpose(tensor_2), tensor_3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [97]:
tf.matmul(tensor_2, tf.transpose(tensor_3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

**Matrix multiplication is also known as dot product**


*   tf.matmul
*   tf.tensordot



In [98]:
tf.tensordot(tf.transpose(tensor_2), tensor_3, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Generally we use transpose (rather than reshape) for matric multiplication

### Change the data type of tensor

In [99]:
# Create a tensor with default datatype
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [101]:
C = tf.constant([1, 4])
C.dtype

tf.int32

In [102]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

### Aggregating Tensors

Aggregation == condensing tensors from multiple values down to smaller amounts of values

*   Get the absolute value
*   Get the minimum
*   Get the maximum
*   Get the sum


In [107]:
# Define a tensor
D = tf.constant([-2, -3])
E = tf.constant([-12, -13])
D, E

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([-12, -13], dtype=int32)>)

In [108]:
# Get the absolute Value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [109]:
# Get the min and max
tf.minimum(D,E)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-12, -13], dtype=int32)>

In [112]:
# get the mean of a tensor
# Create a tensor of random values between 0 and 100 of size 50
F = tf.constant(np.random.randint(0, 100, size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([40, 70, 51, 29, 62,  2, 31, 54, 61, 24, 34, 69, 21, 95, 82, 38, 95,
       74, 11, 54, 77, 41, 73, 90, 30, 65, 34, 95, 22,  4,  9, 69, 11, 22,
       14, 46,  4, 86, 25, 56, 99, 76, 42, 33, 44,  6, 13, 53, 20, 17])>

In [113]:
F.ndim, F.shape, tf.size(F)

(1, TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [116]:
tf.reduce_min(F), tf.reduce_max(F), tf.reduce_mean(F), tf.reduce_sum(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=45>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2273>)

In [127]:
#Find variance and standard deviation of F
meanVal = tf.reduce_mean(F)
sizeVal = tf.size(F).numpy()

tmp1 = F - meanVal
tmp2 = tf.square(tmp1)
variance = tf.divide(tf.reduce_sum(tmp2), sizeVal)
stdDev = tf.sqrt(variance)
print("variance:", variance)
print("standard deviation: ", stdDev)

variance: tf.Tensor(791.58, shape=(), dtype=float64)
standard deviation:  tf.Tensor(28.135031544322107, shape=(), dtype=float64)


In [130]:
# With built in functions
import tensorflow_probability as tfp
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=float16, numpy=791.0>

In [134]:
# Find the std dev and variance
tf.math.reduce_std(tf.cast(F,dtype=tf.float32)), tf.math.reduce_variance(tf.cast(F,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=28.13127>,
 <tf.Tensor: shape=(), dtype=float32, numpy=791.36835>)

### Find the positional maximum and minimum

* Index of max and min values in a tensor

In [132]:
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([40, 70, 51, 29, 62,  2, 31, 54, 61, 24, 34, 69, 21, 95, 82, 38, 95,
       74, 11, 54, 77, 41, 73, 90, 30, 65, 34, 95, 22,  4,  9, 69, 11, 22,
       14, 46,  4, 86, 25, 56, 99, 76, 42, 33, 44,  6, 13, 53, 20, 17])>

In [133]:
tf.argmax(F), tf.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=40>,
 <tf.Tensor: shape=(), dtype=int64, numpy=5>)

In [135]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [136]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor

Removing all single dimensions of a tensor

In [142]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [144]:
G_squuezed = tf.squeeze(G)
G_squuezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding

In [147]:
# Create a list of indices
some_list = [0, 1, 2, 3] # red, green, blue, purple
some_list

In [149]:
# Perform one hot encoding
one_hot_list = tf.one_hot(some_list,depth=4)
one_hot_list

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [150]:
# Specify custoom values for one_hot
one_hot_list = tf.one_hot(some_list,depth=4,on_value="yo I love data science", off_value="I also love dancing")
one_hot_list

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love data science', b'I also love dancing',
        b'I also love dancing', b'I also love dancing'],
       [b'I also love dancing', b'yo I love data science',
        b'I also love dancing', b'I also love dancing'],
       [b'I also love dancing', b'I also love dancing',
        b'yo I love data science', b'I also love dancing'],
       [b'I also love dancing', b'I also love dancing',
        b'I also love dancing', b'yo I love data science']], dtype=object)>

In [151]:
# Play around with orders
one_hot_list = tf.one_hot(some_list,depth=3)
one_hot_list

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [152]:
# Play around with orders
one_hot_list = tf.one_hot(some_list,depth=5)
one_hot_list

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

### Squaring, log, square root

In [154]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [159]:
tf.square(H), tf.sqrt(tf.cast(H, tf.float32)), tf.math.log(tf.cast(H, tf.float32))

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
        2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246], dtype=float32)>)

### Tensors and Numpy

In [160]:
# Create a tensor from numpy array
J = tf.constant(np.array([1., 2., 3.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [161]:
# Convert tesnor back to numpy array
np.array(J), type(np.array(J))

(array([1., 2., 3.]), numpy.ndarray)

In [163]:
# Another way
J.numpy(), type(J.numpy()), J.numpy()[1]

(array([1., 2., 3.]), numpy.ndarray, 2.0)

In [164]:
numpy_J = tf.constant(np.array([1., 2., 3.]))
tensor_J = tf.constant([1., 2., 3.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]